# Generated by Django 3.1.7 on 2021-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210330_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_city_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_state_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='sipping_information',
            field=models.ManyToManyField(blank=True, related_name='shipping_address', to='users.ShippingInformation'),
        ),
    ]
