# Generated by Django 3.1.5 on 2021-02-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author_biography'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='genre',
        ),
    ]
