# Generated by Django 3.1.7 on 2021-03-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20210317_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
