# Generated by Django 3.1.5 on 2021-04-08 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bookstore', '0011_auto_20210324_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_save', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at_save', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer_save', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
    ]
